/*
 * Translator service between a srb2kart server and json
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ServerInfo struct {

	PacketVersion uint8 `json:"PacketVersion"`

	Application string `json:"Application"`

	Version uint8 `json:"Version"`

	SubVersion uint8 `json:"SubVersion"`

	NumberOfPlayer uint8 `json:"NumberOfPlayer"`

	MaxPlayers uint8 `json:"MaxPlayers"`

	GameType uint8 `json:"GameType"`

	ModifiedGame bool `json:"ModifiedGame"`

	CheatsEnabled bool `json:"CheatsEnabled"`

	KartVars uint8 `json:"KartVars"`

	FileNeededNum uint8 `json:"FileNeededNum"`

	Time uint32 `json:"Time"`

	LevelTime uint32 `json:"LevelTime"`

	ServerName string `json:"ServerName"`

	MapName string `json:"MapName"`

	MapTitle string `json:"MapTitle"`

	MapMD5 [16]byte `json:"MapMD5"`

	ActNum uint8 `json:"ActNum"`

	IsZone bool `json:"IsZone"`

	HttpSource string `json:"HttpSource"`

	FileNeeded []FileNeededInner `json:"FileNeeded"`
}

// AssertServerInfoRequired checks if the required fields are not zero-ed
func AssertServerInfoRequired(obj ServerInfo) error {
	for _, el := range obj.FileNeeded {
		if err := AssertFileNeededInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseServerInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ServerInfo (e.g. [][]ServerInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseServerInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aServerInfo, ok := obj.(ServerInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertServerInfoRequired(aServerInfo)
	})
}
